---

- name: install list of packages, debian based
  apt:
    pkg:
    - net-tools # netstat
    - jq # json tool
    - vim
    - curl
    - whois
    - zip
    - unzip
    - ntpdate
    - inetutils-traceroute
    #- python3
    #- python3-pip
    #- python3-setuptools
    state: present
    update_cache: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: install list of packages, RHEL
  yum:
    name:
    - net-tools # netstat
    - jq # json tool
    - vim
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

